### ISSUE TITLE
File loses execute permission after saving

### ISSUE THREAD

**Issue by jdanosborne** [phpfmt/vim-phpfmt#10]
I'm finding vim-phpfmt very useful for formatting my php files but for some reason I have to chmod it to set the execute flag after each save. The script is run from a cron job and starts...

#!/usr/bin/php-5.4-cli
<?php

Is there a way to avoid having to chmod after every save?

TIA

Dan

**Comment by ccirello** [comment]
It is a bug. I am going to fix it ASAP

**Comment by jdanosborne** [comment]
Many thanks for your prompt attention :)

Dan

**Comment by ccirello** [comment]
upgrade to https://github.com/phpfmt/vim-phpfmt/releases/tag/1.1.2

**Comment by jdanosborne** [comment]
:PluginInstall from within vim seems to have picked up the latest version and it now keeps the execute permission after saving - thank you.

Dan
