### ISSUE TITLE
Auto indenting multi line concatenations

### ISSUE THREAD

**Issue by snowiow** [phpfmt/vim-phpfmt#12]
Hi, I've got the following problem:
![initial](https://cloud.githubusercontent.com/assets/3718461/10610712/547979d4-7749-11e5-9630-2d11125f445b.png)
Then I'm calling phpfmt and out comes:
![after_save](https://cloud.githubusercontent.com/assets/3718461/10610739/75745370-7749-11e5-86c8-946badf2e193.png)
But I want to keep it the way it was before. I couldn't really find the option which is turning this feature off. 
Could you please tell me what option it is? Thanks in advance.

**Comment by Shaked** [comment]
@snowiow - I am very sorry for this bug, I will fix it ASAP.

**Comment by ccirello** [comment]
@snowiow this is a rather complex issue. There is a on-going effort that fix most cases - although it is not a finished job, it should be usable for the case you just posted. @Shaked is working on more cases to make it more robust.

Upgrade to https://github.com/phpfmt/php.tools/releases/tag/16.1.1

**Comment by snowiow** [comment]
Yes I can believe that. Thanks for your efforts :)
