### ISSUE TITLE
:w empties file occasionally

### ISSUE THREAD

**Issue by jdanosborne** [phpfmt/vim-phpfmt#13]
Twice now on saving a file in vim I end up with 0 lines, 0 columns.

Any pointers at how to troubleshoot this as my suspicion is that it is the re-formatting triggered on save that is doing it.

TIA

Dan

**Comment by ccirello** [comment]
I have never seen if behaving like that before. But I wonder if it is a timeout. If so, try to run the formatter with php7,which is much faster.

**Comment by jdanosborne** [comment]
I'm not php7-ready I'm afraid. Can I change it to only do the processing on demand rather than on every save? Then I could save a copy before reformating just in case ( I only have vim 7.2 so can't use 'persistent undo').

Dan

**Comment by ccirello** [comment]
Sure  just change https://github.com/phpfmt/vim-phpfmt/blob/master/plugin/phpfmt.vim
